#include "pumpconfig/lohse_10_5.hpp"

namespace pumpconfig {

// Lohse et al. (2016) optical-superlattice Thouless pump
// [Nature Physics 12, 350; reference/lohes_nature_physics.pdf], mapped to the
// main.cpp cosine convention. All numbers below are derived and cross-checked
// in rice_mele_reference/lohes_experience/ (index.html + make_lohse_reference.py).
//
// Paper potential:  V = Vs sin^2(pi x/ds + pi/2) + Vl sin^2(pi x/dl - phi/2),
//                   Vs = 10 E_rs, Vl = 20 E_rl = 5 E_rs, dl = 2 ds.
// main.cpp form:    V^m = -Vs^m cos(4 pi x/a) - Vl^m cos(2 pi x/a + phi^m)
// with cosine amplitudes HALF the sin^2 depths (Vs^m = 5 E_rs, Vl^m = 2.5 E_rs)
// and phi^m(s) = 3 pi/2 - phi(s). The code recoil (k = 2 pi/a = pi/d_s) IS the
// short-lattice recoil E_rs, so the depths-over-recoil below are 5.0 and 2.5.
//
// Pump direction: phi^m DECREASES from 3 pi/2 (the paper's forward pump seen
// through the pure-translation frame map), so the packet moves +a per cycle:
// expect delta polarization_cell of about +1, OPPOSITE to legacy_prb_3_3
// (which drives phi^m increasing and pumps -a).
PumpConfig make_lohse_10_5_config() {
    PumpConfig cfg;
    cfg.config_name = "lohse_10_5";
    cfg.model = "legacy_prb";

    cfg.N = 1;
    cfg.K = 16;

    // Lattice and energy scale (code units hbar = m = 1, E_rs = pi^2/32).
    cfg.lattice_a = 8.0;
    set_lattice_depths_over_recoil(cfg, 5.0, 2.5);

    // Time grid. T = 500 pi code units = 154 pi hbar/E_rs: with the
    // gap-adaptive schedule this sits at P0 ~ 0.997 (band-0 fidelity),
    // matching the quality of the Vs3Vl3 success case. For 99.9% use
    // 1000 pi (= 308 pi hbar/E_rs); a uniform drive would need ~12970 pi.
    // At dt = 2e-3 this is ~785k RK4 steps (roughly 5x the Vs3Vl3 run).
    cfg.pump_period = 500.0 * pi;
    cfg.total_time = 1.5;
    cfg.dt = 0.002;

    // Gap-adaptive phase schedule, main.cpp convention (phi^m decreasing
    // from 3 pi/2; dphi/dt ~ g(phi)^2 with g_pump = 0.111 E_rs at the
    // symmetric double-well phases).
    cfg.phase_schedule_csv =
        "rice_mele_reference/lohes_experience/gap_adaptive_lohse_maincpp_schedule.csv";

    // Output cadence: every 75 steps ~ 10.5k trace samples / snapshot events,
    // the same count as the Vs3Vl3 run (which sampled every 25 of 251k steps).
    cfg.snapshot_every = 0;
    cfg.trace_every = 25;

    // TDVP linear solve (unchanged from legacy_prb_3_3).
    cfg.lambda_C = 1.0e-8;
    cfg.rcond = 1.0e-4;

    // Initial state: band-0 Wannier of the phi^m = 3 pi/2 symmetric double
    // well (two peaks over sites x = 0 and 4), fitted with 11 Gaussians
    // (fidelity 0.9989) plus 5 path-pad Gaussians seeded toward +x.
    // Generated by rice_mele_reference/lohes_experience/make_lohse_initial_basis.py.
    cfg.basis_from = "initial_state/Vs10Ers_Vl5Ers/initial_lohse_N1_K16.csv";
    cfg.out_root = "out/dtscan_lohse/dt0p002";

    // Labels written to config.txt/summary.txt.
    cfg.potential_label = "legacy_prb_cosine";
    cfg.reference_units_label = "lohse_nphys2016_halfdepth_Ers";
    cfg.expanded_potential_label = "-Vs*cos(4*pi*x/a)-Vl*cos(2*pi*x/a+phi)";

    return cfg;
}

}  // namespace pumpconfig
